### ISSUE TITLE
Unable to make it work with Watir > 5.0

### ISSUE THREAD

**Issue by shideneyu** [p0deje/watir-scroll#5]
I found this issue while I wanted to try your gem. i think that the dependancy do not allow a newer version of Watir ? And thanks for your good work so far !

```
/home/sidney/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate watir-scroll-0.3.0, because watir-5.0.0 conflicts with watir (>= 6.0) (Gem::ConflictError)
	from /home/sidney/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
	from /home/sidney/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
	from /home/sidney/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems.rb:195:in `try_activate'
	from /home/sidney/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /home/sidney/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
```

**Comment by shideneyu** [comment]
That was my error sorry. This was the opposite, watir-scroll does not allow the usage of an older version of watir.

As for reference, Watir 6.0 was not working for me. I made it work by uninstalling ´commonwatir´
